### Joint PDF (discrete)

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from datascience import *
from prob140 import *
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
plt.style.use('fivethirtyeight')

Creating probability distribution

In [3]:
dist = Table().domain([129,130,131], [15,16])
dist

X    | Y
129  | 15
129  | 16
130  | 15
130  | 16
131  | 15
131  | 16

In [4]:
dist = dist.probabilities([0.12,0.08,0.42,0.28,0.06,0.04])
dist

X=129  X=130  X=131
Y=16   0.08   0.28   0.04
Y=15   0.12   0.42   0.06

Calculating marginal probabilities

In [5]:
dist.marginal('Y')

X=129  X=130  X=131  Sum: Marginal of Y
Y=16   0.08   0.28   0.04                 0.4
Y=15   0.12   0.42   0.06                 0.6

Marginal probability distribution

In [6]:
dist.marginal_dist("Y")

Value | Probability
15    | 0.6
16    | 0.4

Conditional Probabilities (X|Y)

In [7]:
dist.conditional_dist("X", "Y")

X=129  X=130  X=131  Sum
Dist. of X | Y=16    0.2    0.7    0.1  1.0
Dist. of X | Y=15    0.2    0.7    0.1  1.0
Marginal of X        0.2    0.7    0.1  1.0

Conditional Probabilities (Y|X)

In [8]:
dist.conditional_dist("Y", "X")

Dist. of Y | X=129  Dist. of Y | X=130  Dist. of Y | X=131  \
Y=16                 0.4                 0.4                 0.4   
Y=15                 0.6                 0.6                 0.6   
Sum                  1.0                 1.0                 1.0   

      Marginal of Y  
Y=16            0.4  
Y=15            0.6  
Sum             1.0

Covariance

In [11]:
dist = Table().domain([129,130,131], [15,16])

np.cov(dist['X'],dist['Y'])

array([[0.8, 0. ],
       [0. , 0.3]])

Correlation

In [12]:
np.cov(dist['X'],dist['Y'])/dist['X'].std()*dist['Y'].std()

array([[0.48989795, 0.        ],
       [0.        , 0.18371173]])

Conditional Mean

In [13]:
dist = Table().domain([129,130,131], [15,16])
dist = dist.probabilities([0.12,0.08,0.42,0.28,0.06,0.04])
display(dist)
d=dist.marginal_dist("Y")

X=129  X=130  X=131
Y=16   0.08   0.28   0.04
Y=15   0.12   0.42   0.06

In [14]:
d

Value | Probability
15    | 0.6
16    | 0.4

In [15]:
d['E']=d['Value']*d['Probability']

In [16]:
d

Value | Probability | E
15    | 0.6         | 9
16    | 0.4         | 6.4

In [17]:
values=d['Value']

In [18]:
values[::-1].sort()

In [19]:
values

array([16, 15])

In [20]:
z=dist.conditional_dist("Y", "X").transpose()

In [21]:
z=dist.conditional_dist("Y", "X").drop(index=['Sum'])

In [22]:
z['values']=values

In [23]:
z

Dist. of Y | X=129  Dist. of Y | X=130  Dist. of Y | X=131  \
Y=16                 0.4                 0.4                 0.4   
Y=15                 0.6                 0.6                 0.6   

      Marginal of Y  values  
Y=16            0.4      16  
Y=15            0.6      15

In [24]:
z['E_marginal,Dist. of Y | X=129']=z['Dist. of Y | X=129']*z['values']
z['E_marginal,Dist. of Y | X=130']=z['Dist. of Y | X=130']*z['values']
z['E_marginal,Dist. of Y | X=131']=z['Dist. of Y | X=131']*z['values']


In [36]:
z.loc['Sum']= z.sum(axis=0)

In [37]:
z

Dist. of Y | X=129  Dist. of Y | X=130  Dist. of Y | X=131  \
Y=16                 0.4                 0.4                 0.4   
Y=15                 0.6                 0.6                 0.6   
Sum                  1.0                 1.0                 1.0   

      Marginal of Y  values  E_marginal,Dist. of Y | X=129  \
Y=16            0.4    16.0                            6.4   
Y=15            0.6    15.0                            9.0   
Sum             1.0    31.0                           15.4   

      E_marginal,Dist. of Y | X=130  E_marginal,Dist. of Y | X=131  
Y=16                            6.4                            6.4  
Y=15                            9.0                            9.0  
Sum                            15.4                           15.4

Conditional Variance

In [39]:
z.loc['Sum']['E_marginal,Dist. of Y | X=129']

15.399999999999999

In [42]:
z['V_marginal,Dist. of Y | X=129']=((z['values']-z.loc['Sum']['E_marginal,Dist. of Y | X=129'])**2)*z['Dist. of Y | X=129']
z['V_marginal,Dist. of Y | X=130']=((z['values']-z.loc['Sum']['E_marginal,Dist. of Y | X=130'])**2)*z['Dist. of Y | X=130']
z['V_marginal,Dist. of Y | X=131']=((z['values']-z.loc['Sum']['E_marginal,Dist. of Y | X=131'])**2)*z['Dist. of Y | X=131']


In [43]:
z

Dist. of Y | X=129  Dist. of Y | X=130  Dist. of Y | X=131  \
Y=16                 0.4                 0.4                 0.4   
Y=15                 0.6                 0.6                 0.6   
Sum                  1.0                 1.0                 1.0   

      Marginal of Y  values  E_marginal,Dist. of Y | X=129  \
Y=16            0.4    16.0                            6.4   
Y=15            0.6    15.0                            9.0   
Sum             1.0    31.0                           15.4   

      E_marginal,Dist. of Y | X=130  E_marginal,Dist. of Y | X=131  \
Y=16                            6.4                            6.4   
Y=15                            9.0                            9.0   
Sum                            15.4                           15.4   

      V_marginal,Dist. of Y | X=129  V_marginal,Dist. of Y | X=130  \
Y=16                          0.144                          0.144   
Y=15                          0.096                          0.096   
Sum                         243.360                        243.360   

      V_marginal,Dist. of Y | X=131  
Y=16                          0.144  
Y=15                          0.096  
Sum                         243.360

### Joint PDF(Continous)

Probability from a joint function

In [45]:
f=lambda x,y:8*x*y
from scipy.integrate import dblquad

In [47]:
prob=dblquad(f,0.5,1,0,0.5)
print(prob[0])

0.375
